name: Setup python

inputs:
  python-version:
    default: "3.10"
    required: false
    description: "python version"

  poetry-version:
    default: "1.2.2"
    required: false
    description: "poetry version"

runs:
  using: composite
  steps:
    - name: Setup python environment
      uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
      with:
        python-version: ${{ inputs.python-version }}

    - name: Make poetry environment
      run: |
        pip install poetry
        poetry install
